title: "0x7FFFFFFF"
description: "Kion's blog"
author:
  name: "Kion-Miyasaka"
  email: "k@declspec.cloud"
  url: "https://www.declspec.cloud"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5 
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "pages"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Y. Liao"
year : "2017"

collections:
  maths:
    output: true
    permalink: /:collection/:name

defaults:
  - 
    values:
      layout: "page"
